# Generated by Django 4.1.5 on 2023-01-21 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        # with triple double quotes, we can write sql in multiline
        migrations.RunSQL("""
        INSERT INTO store_collection (title)
        VALUES ('collection1')
        """, """
        DELETE FROM store_collection 
        WHERE title='collection1'
        """)
    ]
